name: Release
on: push

jobs:
  release:
    name: release
    runs-on: ubuntu-18.04
    outputs:
      release_version: ${{ steps.release.outputs.new_release_version }}
      version_upgrade: ${{ steps.release.outputs.version_upgrade }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: release
        id: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npx semantic-release
          echo "::set-output name=version_upgrade::$(npx semantic-release | grep "no new version is released")"
          echo "::set-output name=new_release_version::$(git describe --tags $(git rev-list --tags --max-count=1))"

      - name: check
        run: |
          echo ${{ steps.release.outputs.new_release_version }}
          echo ${{ steps.release.outputs.version_upgrade }}

  test:
    name: testing
    runs-on: ubuntu-18.04
    needs: [release]
    if: ${{ !needs.release.outputs.version_upgrade }}
    steps:
      - name: Test variables output
        run: |
          echo "test"
          echo ${{ needs.release.outputs.release_version }}
          echo ${{ needs.release.outputs.version_upgrade }}
